//
//  ChatStyleKit.swift
//  miaomiao.v2
//
//  Created by minbaba on 16/8/15.
//  Copyright (c) 2016 MiaoquTech Inc. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class ChatStyleKit : NSObject {

    //// Drawing Methods

    public class func drawChatBunble(bunbleFrame bunbleFrame: CGRect = CGRectZero, showBunble: Bool = true, isSelf: Bool = true) {

        //// Group
        //// BunbleBack Drawing
        let bunbleBackPath = UIBezierPath(roundedRect: bunbleFrame, byRoundingCorners: [UIRectCorner.TopRight, UIRectCorner.BottomLeft, UIRectCorner.BottomRight], cornerRadii: CGSizeMake(20, 20))
        bunbleBackPath.closePath()
        if showBunble {
            (isSelf ? UIColor(hexStr: "64C5FF"): UIColor.whiteColor()).setFill()
        } else { UIColor.clearColor().setFill() }
        bunbleBackPath.fill()
    }

    public class func drawSeprator(color: UIColor) {
        
        //// seprator Drawing
        let sepratorPath = UIBezierPath(rect: CGRectMake(0, -0.5, screenWidth, 1))
        color.setFill()
        sepratorPath.fill()
    }
    
    public class func drawGroupIcon(images: UIImage...) {
        
        guard images.count >= 3 else { return }
        
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()
        
        //// Oval Drawing
        var image = images[0]
        
        let ovalPath = UIBezierPath()
        ovalPath.moveToPoint(CGPointMake(43, 15.5))
        ovalPath.addCurveToPoint(CGPointMake(27.5, 31), controlPoint1: CGPointMake(43, 24.06), controlPoint2: CGPointMake(36.06, 31))
        ovalPath.addCurveToPoint(CGPointMake(12, 15.5), controlPoint1: CGPointMake(18.94, 31), controlPoint2: CGPointMake(12, 24.06))
        ovalPath.addCurveToPoint(CGPointMake(27.5, 0), controlPoint1: CGPointMake(12, 6.94), controlPoint2: CGPointMake(18.94, 0))
        ovalPath.addCurveToPoint(CGPointMake(43, 15.5), controlPoint1: CGPointMake(36.06, 0), controlPoint2: CGPointMake(43, 6.94))
        ovalPath.closePath()
        CGContextSaveGState(context)
        ovalPath.addClip()
        CGContextScaleCTM(context, 1, -1)
        CGContextDrawTiledImage(context, CGRectMake(12, 4, image.size.width, image.size.height), image.CGImage)
        CGContextRestoreGState(context)
        
        
        //// Oval 2 Drawing
        image = images[1]
        
        let oval2Path = UIBezierPath()
        oval2Path.moveToPoint(CGPointMake(31, 39.5))
        oval2Path.addCurveToPoint(CGPointMake(15.5, 55), controlPoint1: CGPointMake(31, 48.06), controlPoint2: CGPointMake(24.06, 55))
        oval2Path.addCurveToPoint(CGPointMake(0, 39.5), controlPoint1: CGPointMake(6.94, 55), controlPoint2: CGPointMake(0, 48.06))
        oval2Path.addCurveToPoint(CGPointMake(15.5, 24), controlPoint1: CGPointMake(0, 30.94), controlPoint2: CGPointMake(6.94, 24))
        oval2Path.addCurveToPoint(CGPointMake(31, 39.5), controlPoint1: CGPointMake(24.06, 24), controlPoint2: CGPointMake(31, 30.94))
        oval2Path.closePath()
        CGContextSaveGState(context)
        oval2Path.addClip()
        CGContextScaleCTM(context, 1, -1)
        CGContextDrawTiledImage(context, CGRectMake(0, -20, image.size.width, image.size.height), image.CGImage)
        CGContextRestoreGState(context)
        
        
        //// Oval 3 Drawing
        image = images[2]
        
        let oval3Path = UIBezierPath()
        oval3Path.moveToPoint(CGPointMake(55, 39.5))
        oval3Path.addCurveToPoint(CGPointMake(39.5, 55), controlPoint1: CGPointMake(55, 48.06), controlPoint2: CGPointMake(48.06, 55))
        oval3Path.addCurveToPoint(CGPointMake(24, 39.5), controlPoint1: CGPointMake(30.94, 55), controlPoint2: CGPointMake(24, 48.06))
        oval3Path.addCurveToPoint(CGPointMake(39.5, 24), controlPoint1: CGPointMake(24, 30.94), controlPoint2: CGPointMake(30.94, 24))
        oval3Path.addCurveToPoint(CGPointMake(55, 39.5), controlPoint1: CGPointMake(48.06, 24), controlPoint2: CGPointMake(55, 30.94))
        oval3Path.closePath()
        CGContextSaveGState(context)
        oval3Path.addClip()
        CGContextScaleCTM(context, 1, -1)
        CGContextDrawTiledImage(context, CGRectMake(24, -20, image.size.width, image.size.height), image.CGImage)
        CGContextRestoreGState(context)
    }
}
